### ISSUE TITLE
GET /api/pasties

### ISSUE THREAD

**Issue by shamsup** [HackerPaste/HackerPaste#15]
If a user is logged in, return a list of pasties shared with the logged in user (via group or directly) ordered by the date shared descending.

If no user is logged in, return a list of the newest publicly visible pasties

**Comment by gilbert** [comment]
I recommend leaving public pasties to a separate endpoint `GET /pasties/public`. It separates the two so that you could, for example, see public pasties when you're logged in.

**Comment by shamsup** [comment]
Good call
