### ISSUE TITLE
GET /api/me/pasties

### ISSUE THREAD

**Issue by shamsup** [HackerPaste/HackerPaste#17]
Return pasties created by the specified user that are visible to the currently logged in user

**Comment by gilbert** [comment]
This and #19 are nice-to-have social features. For MVP I recommend starting with `GET /me/pasties` and `GET /me/favorites`, which will return results owned by the logged in user.

**Comment by shamsup** [comment]
Okay. I can drop the `/api` prefix and work with the `me-api` file for requests on the users' own data

**Comment by gilbert** [comment]
Oops, sorry I didn't mean to drop the `/api` prefix. It should be `GET /api/me/favorites`
