### ISSUE TITLE
Favorite Model

### ISSUE THREAD

**Issue by shamsup** [HackerPaste/HackerPaste#42]
- [ ] `Favorite.create( <pastie_id>, <user_uid> )` 
- [ ] `Favorite.delete( <pastie_id>, <user_uid> )`

**Comment by arvinwallace** [comment]
Working on this now. I'm assuming that the parameters for Favorite.create(pastie_id, user_id) are expecting two numbers and not objects correct?

**Comment by arvinwallace** [comment]
These are done.. Tested in my db. results are as expected.

**Comment by shamsup** [comment]
alright, submit a PR then we can check them off
