### ISSUE TITLE
Share Model

### ISSUE THREAD

**Issue by shamsup** [HackerPaste/HackerPaste#43]
- [x] `Share.create( <pastie_id>, <subjects> )`
- [x] `Share.delete( <pastie_id>, <subjects> )`

`<subjects>` is an array of objects with the following properties:
- `subject_type`: `'User'` or `'Group'`
- `subject_uid`: `<user_uid | group_uid>`

ie `{ subject_type: 'User', subject_uid: 'user_alice' }`

**Comment by arvinwallace** [comment]
"<subjects> is an array of objects with the following properties:
subject_type: 'User' or 'Group'
subject_uid: <user_uid | group_uid>"

An array of objects? So  subject_type would = subjects[0].User 
                               -- and---  subject_uid would = subjects[1].user_uid?

**Comment by shamsup** [comment]
well it will look like this 

``` javascript
var subjects = [
  {
    subject_type: 'User',
    subject_uid: 'user_alice'
  },
  {
    subject_type: 'Group',
    subject_uid: 'group1'
  },
]
```

**Comment by arvinwallace** [comment]
I imagine this goes into the pasties_subject table --- so I'm wondering since this table has but three columns:  (one for the "pastie id" and the other two for subject type and subject uid) will I need to supply some logic to this method and pick which object in the array should fill up the last two columns?

**Comment by shamsup** [comment]
all<sup>1</sup> of the `subjects` should be inserted. 

<sup>1</sup>taking into consideration whether the user has permission to share the given pastie with the given subjects.

**Comment by gilbert** [comment]
Don't worry about authorization; that will be done by the express endpoint using makerpass. You can insert all the subjects that the model is given.

**Comment by shamsup** [comment]
On that note, what rules determine who can share inside of groups? Can any member of a group share things to it? Or can only instructors and fellows share?

**Comment by arvinwallace** [comment]
Ok working on this now.

**Comment by shamsup** [comment]
We also need to add errors to these methods, so that if a request comes in for a pastie that doesn't exist, it gives a NotFound error, and deleting a share that doesn't exist should also give a NotFound error

**Comment by gilbert** [comment]
Deleting a share shouldn't throw. In both cases the share is gone, so no need for an error.
